<div class="row">
  <div class="col-md-offset-3 col-md-6">
    <h1 class="text-center">Unesi novi post!</h1>
    <?php
      if(isset($errors))
      foreach ($errors as $error) {
        echo '<div class="alert alert-danger" role="alert">'.$error.'</div>';
      }

     ?>
  </div>
</div>

<div class="row">
  <div class="col-md-offset-3 col-md-6">
      <?php echo $this->tag->form("post/add"); ?>

       <div class="form-group">
          <label for="email">Email</label>
          <?php echo $this->tag->textField(array("name" => "email", "class" => "form-control")) ?>
       </div>

      <div class="form-group">
       <label for="tekst">Tekst</label>
       <?php echo $this->tag->textArea(array(
          "tekst",
          "class"=> "form-control",
          "cols" => "30",
          "rows" => 10
      )) ?>
      </div>

          <button type="submit" class="btn btn-default">Dodaj</button>


      </form>
  </div>
</div>
<!--{% if errors is defined %}
    {%for error in errors%}
      <p>{{error}}</p>
    {% endfor %}
{% endif %}

<form method="post">
<div class="form-group">
  <label for="email">Email</label>
  {{ text_field('email')}}
</div>
<div class="form-group">
  <label for="tekst">Tekst</label>
   {{text_area("tekst","aaa", "ccc" ,"cols": "50", "rows": 20) }}

    {{ submit_button('Unesi') }}
    {{ link_to('post/', 'Nazad') }}

</form>
-->
