<div class="row">
<div class="col-md-offset-3 col-md-6">
 <h1 class="text-center">Popis Postova!</h1>
</div>
</div>

<div class="row">

<?php foreach ($page->items as $item) {
 echo '<div class="row">';
   echo '<div class="col-md-offset-3 col-md-6">';
     echo '<textarea class="form-control" rows="3">';
       echo $item->tekst;
   echo '</textarea>';
 echo "</div> </div>";
?>
<div class="row">
<div class="col-md-offset-3 col-md-2">
<p>
<?= $this->tag->linkTo(array('post/delete/'.$item->id, 'Pobrisi', 'class' => 'btn btn-info form-control', 'role' => 'button')) ?>
</p>

</div>
</div>

 <?php
}
?>
</div>

<?php if($page->total_pages > 1) : ?>

<div class="row">
  <div class="col-md-offset-3 col-md-6">
   <div class="text-center">

    <nav>
      <ul class="pagination">
        <li>
          <a href="/twitter-clone/post?page=<?= $page->before; ?>" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
        <?php
          $index = 1;
          foreach ($page->items as $item) {
          echo "<li>";
          echo '<a href="/twitter-clone/post?page='.$index.'">'.$index.'</a>';
          echo '</li>';
          $index++;

          if($index > $page->total_pages) break;

        }?>

        <li>
          <a href="/twitter-clone/post?page=<?= $page->next; ?>" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      </ul>
    </nav>

       <a href="/twitter-clone/post/">First</a>
       <a href="/twitter-clone/post?page=<?= $page->before; ?>">Previous</a>
       <a href="/twitter-clone/post?page=<?= $page->next; ?>">Next</a>
       <a href="/twitter-clone/post?page=<?= $page->last; ?>">Last</a>

       <?php echo "<br/>You are in page ", $page->current, " of ", $page->total_pages; ?>

   </div>
  </div>
</div>

<?php endif; ?>


<!--<div class="row">
  <div class="col-md-offset-3 col-md-2">
  <p>   $this->tag->linkTo(array('post/add', 'Dodaj Post', 'class' => 'btn btn-primary ', 'role' => 'button')) ?></p>
  </div>
</div>*/-->

<!--{% for post in postovi %}

  <div class="row">
    <div class="col-md-6">
      {{post.tekst}} {{ link_to('post/delete/' ~ post.id, 'Obrisi')}}
    </div>
  </div>
{% endfor %}

<p>
  {{ link_to('post/add/', 'Dodaj Post')}}
</p>
-->
